# Generated by Django 4.2.10 on 2024-02-27 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.base
import django.views.generic.edit


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratingAuthor', models.SmallIntegerField(default=0, verbose_name='Рейтинг:')),
                ('authorUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Категория:')),
                ('subscribers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryType', models.CharField(choices=[('NW', 'Новость'), ('AR', 'Статья')], default='AR', max_length=2, verbose_name='Статья/Новость:')),
                ('dateCreation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания:')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок:')),
                ('text', models.TextField(verbose_name='Текст поста:')),
                ('rating', models.SmallIntegerField(default=0, verbose_name='Рейтинг:')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnews.author')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='CategoryView',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appnews.category')),
            ],
            bases=(django.views.generic.edit.FormView, django.views.generic.base.View, 'appnews.category'),
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryThrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnews.category')),
                ('postThrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnews.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='postArticleCategory',
            field=models.ManyToManyField(through='appnews.PostCategory', to='appnews.category'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Тут хелп текст к коментариям', verbose_name='Коментарий:')),
                ('dateCreation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания:')),
                ('rating', models.SmallIntegerField(default=0, verbose_name='Рейтинг:')),
                ('commentPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnews.post')),
                ('commentUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Коментарий',
                'verbose_name_plural': 'Коментарии',
            },
        ),
    ]
