# Generated by Django 4.2.10 on 2024-03-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnews', '0002_alter_post_options_alter_postcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoryType',
            field=models.CharField(choices=[('NW', 'Новость'), ('AR', 'Статья')], default='AR', max_length=2, verbose_name='Тип:Статья/Новость:'),
        ),
        migrations.DeleteModel(
            name='CategoryView',
        ),
    ]
