# Generated by Django 4.2.10 on 2024-03-14 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appnews', '0006_alter_post_categorytype_alter_post_datecreation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='categoryThrough',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='appnews.category', verbose_name='Категория:'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='postThrough',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='appnews.post', verbose_name='Пост/Новость:'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='appnews.category', verbose_name='Категории:')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь:')),
            ],
        ),
    ]
